name: Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/prod

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-terraform-role-v1
          aws-region: ap-south-1

      - name: Terraform init 
        working-directory: .github/workflow/githubactions-aws-26
        run: terraform init

      - name: Show Files  
        run: |
          pwd
          ls -la
          find . -name "*.tf"



      - name: Terraform Validate
        working-directory: .github/workflows/githubactions-aws-26
        run: terraform validate  
               
       
      - name: Terraform Plan
        working-directory: .github/workflows/githubactions-aws-26
        run: terraform plan -out=tfplan    
   

      - name: Terraform Apply
        working-directory: .github/workflows/githubactions-aws-26
        run: terraform apply -auto-approve tfplan  
